name: ML Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python train.py

      - name: Upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: model_info.txt


  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model_info

      - name: Install dependencies
        run: |
          pip install mlflow

      - name: Check threshold
        run: |
          python check_threshold.py

      - name: Mock Docker build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
