name: ML Pipeline

on:
  push:
    branches:
      - "**"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn

      - name: Train model
        run: |
          python train.py

      - name: Upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model info
        uses: actions/download-artifact@v4
        with:
          name: model_info

      - name: Check threshold
        run: |
          python check_threshold.py

      - name: Mock deploy
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
